Repository Boutique-Cinema/boutique-cinema-react, pull requests merged in 2024-09, with the labels that each got.

#1 test : 커밋 테스트
  src/pages/MainPage.jsx
Labels: test

#2 test commit
  src/pages/MainPage.jsx
Labels: test

#4 modify : 메인페이지 수정 테스트
  src/pages/MainPage.jsx
Labels: test

#7 modify : MainPage 수정
  src/pages/MainPage.jsx
Labels: test

#28 feat : 기본 레이아웃 구조 설계 - 사용자 헤더 완성(#8)
  .prettierrc
  package-lock.json
  package.json
  public/favicon.ico
  public/favicon.png
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/roca-two-bold.ttf
  public/search-icon.png
  src/App.jsx
  src/components/common/Logo.jsx
  src/components/common/Search.jsx
  src/components/layouts/AdminHeader.jsx
  src/components/layouts/AdminSidebar.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/MemberHeader.jsx
  src/components/layouts/MemberSidebar.jsx
  src/components/layouts/Nav.jsx
  src/layouts/BasicLayout.jsx
  src/routes/router.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: feat, setting

#34 feat : footer 추가(#8)
  public/logo.png
  src/components/common/Logo.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/MemberHeader.jsx
  src/components/layouts/Nav.jsx
  src/layouts/BasicLayout.jsx
  src/pages/MainPage.jsx
  src/routes/router.jsx
Labels: feat

#35 modify : footer 겹침 수정(#8)
  src/layouts/BasicLayout.jsx
Labels: modify

#36 modify:고객센터 페이지 설계 수정#23
  public/greeting/basic.png
  public/greeting/bg-arm-chair.png
  public/greeting/bg-side-chair.png
  public/greeting/bg-table-chair.png
  public/greeting/bg-wide-chair.png
  public/greeting/couple.jpg
  public/greeting/img-theater-comfort-view02.png
  public/greeting/img-theater-comfort-view03.png
  src/components/layouts/Footer.jsx
  src/pages/greeting/CouplePage.jsx
  src/pages/greeting/TheaterPage.jsx
  src/pages/info/InfoPage.jsx
  src/pages/support/PrivacyPage.jsx
  src/pages/support/ScreenrulePage.jsx
  src/pages/support/TermsPage.jsx
  src/routes/router.jsx
Labels: modify

#39 add: 회원가입 페이지 추가(#31)
  src/components/common/Search.jsx
  src/components/member/JoinComponent.jsx
  src/pages/member/FindInfoPage.jsx
  src/pages/member/JoinPage.jsx
  src/pages/member/LoginPage.jsx
  src/pages/member/ModifyPwpage.jsx
  src/pages/member/support/QnaDetail.jsx
  src/pages/member/support/QnaPage.jsx
  src/pages/member/support/QnaRegister.jsx
  src/routes/router.jsx
Labels: add

#42 Feature#8
  src/components/layouts/AdminHeader.jsx
  src/components/layouts/AdminSidebar.jsx
  src/components/layouts/MemberHeader.jsx
  src/components/layouts/MemberSidebar.jsx
  src/components/layouts/Nav.jsx
  src/layouts/AdminLayout.jsx
  src/layouts/BasicLayout.jsx
  src/routes/router.jsx
  tailwind.config.js
Labels: modify

#44 Feature#37
  public/greeting/bgArmChair.png
  public/greeting/bgSideChair.png
  public/greeting/bgTableChair.png
  public/greeting/bgWideChair.png
  public/greeting/goldclass_10.jpg
  public/greeting/goldclass_11.jpg
  public/greeting/imgTheaterComfortView02.png
  public/greeting/imgTheaterComfortView03.png
  src/components/common/ScrollTop.jsx
  src/pages/greeting/CouplePage.jsx
  src/pages/greeting/TheaterPage.jsx
  src/pages/support/PrivacyPage.jsx
  src/pages/support/TermsPage.jsx
  src/router/greetingRouter.jsx
  src/routes/router.jsx
Labels: feat, modify

#45 add : 회원가입페이지 추가, react-hook-form 의존성 추가(#40)
  package-lock.json
  package.json
  src/components/member/JoinComponent.jsx
Labels: add, modify

#46 add : 마이페이지 예매 내역 페이지 추가(#43)
  src/pages/mypage/MyReservationPage.jsx
  src/routes/router.jsx
Labels: add

#49 modify:고객센터 페이지 초안 완성(#23)
  public/question.png
  src/components/common/Search.jsx
  src/components/layouts/SupportSidebar.jsx
  src/layouts/BasicLayout.jsx
  src/pages/support/NoticeDetailPage.jsx
  src/pages/support/NoticeListPage.jsx
  src/pages/support/QnaDetail.jsx
  src/pages/support/QnaPage.jsx
  src/pages/support/QnaRegister.jsx
  src/routes/greetingRouter.jsx
  src/routes/movieRouter.jsx
  src/routes/router.jsx
  src/routes/supportRouter.jsx
Labels: modify

#47 add, modify : membersAPi.js추가 JoinComponent.jsx 수정(#40)
  src/api/membersApi.js
  src/components/member/JoinComponent.jsx
Labels: add, modify

#52 modify: 메인페이지 기본틀 수정완료 #50
  public/hello.jpg
  public/joker.jpg
  public/love.jpg
  public/veterang.jpg
  src/components/layouts/Footer.jsx
  src/components/layouts/Nav.jsx
  src/pages/MainPage.jsx
  src/pages/support/NoticeListPage.jsx
  src/routes/router.jsx
Labels: modify
