Repository Boutique-Cinema/boutique-cinema-react, pull requests merged in 2024-10, with the labels that each got.

#58 Feature#12 영화 리스트 및 상세페이지 API 연동
  src/api/movie/movieApi.js
  src/pages/MainPage.jsx
  src/pages/movie/MovieDetailPage.jsx
  src/pages/movie/MovieListPage.jsx
  src/pages/support/ScreenrulePage.jsx
  src/routes/movieRouter.jsx
  src/routes/router.jsx
Labels: feat, modify

#61 modify : 로그인 페이지 설계(#57)
  src/components/member/LoginComponent.jsx
  src/pages/member/LoginPage.jsx
  src/routes/router.jsx
Labels: modify

#63 create : 영화 검색 기능 추가(#59)
  src/components/common/Search.jsx
Labels: add

#65 create: 관리자 공지사항(리스트 및 상세페이지) 생성(#64)
  src/components/support/AdminNoticeDetail.jsx
  src/components/support/AdminNoticeList.jsx
  src/pages/info/InfoPage.jsx
  src/router/greetingRouter.jsx
  src/routes/adminSupportRouter.jsx
  src/routes/router.jsx
Labels: add

#66 modify: 사용자공지사항 api연결(#23)
  src/api/support/noticeManager.js
  src/pages/support/NoticeDetailPage.jsx
  src/pages/support/NoticeListPage.jsx
Labels: modify

#67 modify: API연동 완료(#23)
  src/api/support/noticeApi.js
  src/api/support/noticeManager.js
  src/pages/support/NoticeDetailPage.jsx
  src/pages/support/NoticeListPage.jsx
  src/routes/supportRouter.jsx
Labels: feat, modify

#69 feat : 영화 등록,수정,삭제,리스트 페이지 작성과 기능 구현(#51)
  src/api/movieApi.js
  src/components/layouts/AdminHeader.jsx
  src/components/layouts/AdminSidebar.jsx
  src/pages/admin/movie/AdminMovieModifyPage.jsx
  src/pages/admin/movie/AdminMoviePage.jsx
  src/pages/admin/movie/AdminMovieRegisterPage.jsx
  src/routes/adminMovieRouter.jsx
  src/routes/router.jsx
Labels: add, feat

#70 modify : 영화 등록,수정,삭제의 컴포넌트에 포스터 이미지 미리보기 썸네일 기능 추가(#51)
  src/pages/admin/movie/AdminMovieModifyPage.jsx
  src/pages/admin/movie/AdminMovieRegisterPage.jsx
Labels: modify

#71 Modify : 관리자 공지사항 페이지 설계 및 기능추가 #68
  src/api/support/noticeApi.js
  src/components/support/AdminNoticeDetail.jsx
  src/components/support/AdminNoticeList.jsx
  src/pages/support/NoticeDetailPage.jsx
  src/routes/adminSupportRouter.jsx
Labels: add

#72 add, modify, delete : 로그인 기능추가 및 파일 삭제, 추가
  package-lock.json
  src/api/membersApi.js
  src/components/member/JoinComponent.jsx
  src/components/member/LoginComponent.jsx
  src/pages/member/FindInfoPage.jsx
  src/pages/member/JoinPage.jsx
  src/pages/member/LoginPage.jsx
  src/routes/router.jsx
Labels: add, delete, modify

#77 modify: 진우형님 noticeApi 수정(#23)
  src/api/support/noticeApi.js
Labels: add

#78 modify: 영화리스트 영화포스터 출력완료(#12)
  src/api/movie/movieApi.js
  src/pages/movie/MovieDetailPage.jsx
  src/pages/movie/MovieListPage.jsx
Labels: modify

#79 modify: 메인페이지 API 연동 완료(#50)
  src/pages/MainPage.jsx
Labels: modify

#80 modify: serch 영화검색 후 영화 리스트에서 화면 출력 연동완료(#59)
  src/components/common/Search.jsx
  src/pages/movie/MovieListPage.jsx
Labels: modify

#82 modfiy : 로그인페이지 id 입력창 정규식 수정(#57)
  src/pages/member/LoginPage.jsx
Labels: modify

#83 영화 예매 페이지 설계 및 등록 기능 구현(#43)
  package-lock.json
  package.json
  src/App.jsx
  src/api/reservationApi.js
  src/components/common/Search.jsx
  src/components/layouts/MemberHeader.jsx
  src/components/layouts/Nav.jsx
  src/components/reservation/ReservationCalendar.jsx
  src/components/reservation/ReservationMovieList.jsx
  src/components/reservation/ReservationResult.jsx
  src/components/reservation/SeatCount.jsx
  src/components/reservation/SeatTable.jsx
  src/components/reservation/TimeTable.jsx
  src/components/reservation/TimeTableItem.jsx
  src/pages/reservation/ReservationSeatPage.jsx
  src/pages/reservation/ReservationTimePage.jsx
  src/routes/reservationRouter.jsx
  src/routes/router.jsx
  src/styles/calendar.css
  src/util/dateFormatUtil.js
  src/util/reservationUtil.js
Labels: add, feat

#84 modify : 영화 api 요청 수정(#43)
  src/api/movieApi.js
  src/components/reservation/ReservationResult.jsx
  src/pages/reservation/ReservationTimePage.jsx
Labels: modify

#86 modify: 관리자,사용자 고객센터 전체연동 완료(#23)
  src/api/support/noticeApi.js
  src/components/support/AdminNoticeDetail.jsx
  src/components/support/AdminNoticeList.jsx
  src/components/support/AdminNoticeModify.jsx
  src/components/support/AdminNoticeRegister.jsx
  src/pages/info/InfoPage.jsx
  src/pages/support/NoticeDetailPage.jsx
  src/pages/support/NoticeListPage.jsx
  src/pages/support/PrivacyPage.jsx
  src/pages/support/TermsPage.jsx
  src/routes/adminSupportRouter.jsx
Labels: modify

#88 modify: 공지사항Api파일 수정으로 관련파일 업데이트 수정 및 영화 목록페이지, 영화 상세페이지, 영화라우터, 메인페…
  src/api/noticeApi.js
  src/components/common/Search.jsx
  src/components/layouts/Nav.jsx
  src/components/support/AdminNoticeDetail.jsx
  src/components/support/AdminNoticeList.jsx
  src/components/support/AdminNoticeModify.jsx
  src/components/support/AdminNoticeRegister.jsx
  src/pages/MainPage.jsx
  src/pages/movie/MovieDetailPage.jsx
  src/pages/movie/MovieListPage.jsx
  src/pages/support/NoticeDetailPage.jsx
  src/pages/support/NoticeListPage.jsx
  src/routes/movieRouter.jsx
Labels: modify

#89 feat : 사용자 질문 리스트,등록,상세(수정,삭제) 페이지 구현(#87)
  src/api/movieApi.js
  src/api/qnaApi.js
  src/components/layouts/SupportSidebar.jsx
  src/pages/admin/movie/AdminMovieModifyPage.jsx
  src/pages/admin/movie/AdminMoviePage.jsx
  src/pages/support/QnaDetail.jsx
  src/pages/support/QnaDetailPage.jsx
  src/pages/support/QnaPage.jsx
  src/pages/support/QnaRegister.jsx
  src/pages/support/QnaRegisterPage.jsx
  src/routes/supportRouter.jsx
Labels: add, delete, feat

#92 add : 회원관리 리스트 구현 #81
  package-lock.json
  package.json
  src/api/membersApi.js
  src/pages/support/AdminMemberList.jsx
  src/routes/adminMemberRouter.jsx
  src/routes/router.jsx
  src/routes/supportRouter.jsx
Labels: add

#94 add : 예매관리 페이지 구현 #93
  src/api/reservationApi.js
  src/pages/support/AdminReservationPage.jsx
  src/routes/adminReservationRouter.jsx
  src/routes/router.jsx
Labels: add

#95 add, modify : 로그인 리덕스툴킷 설정 추가 및 변경
  package-lock.json
  package.json
  src/hook/useCustomLogin.js
  src/index.js
  src/pages/member/LoginPage.jsx
  src/routes/router.jsx
  src/slice/loginSlice.js
  src/store.js
  src/util/cookieUtil.js
  src/util/jwtUtil.js
Labels: add, modify

#97 modify: 수정요청파일 수정완료(#12)
  package-lock.json
  src/components/layouts/SupportSidebar.jsx
  src/layouts/BasicLayout.jsx
  src/pages/MainPage.jsx
  src/pages/info/InfoPage.jsx
  src/pages/movie/MovieDetailPage.jsx
  src/pages/movie/MovieListPage.jsx
  src/pages/support/NoticeDetailPage.jsx
  src/pages/support/NoticeListPage.jsx
  src/pages/support/ScreenrulePage.jsx
Labels: modify

#102 modify: 공지사항,1:1문의 사이드바 추가 수정(#12)
  src/components/layouts/Footer.jsx
  src/components/layouts/SupportSidebar.jsx
  src/layouts/BasicLayout.jsx
  src/routes/router.jsx
  src/routes/supportRouter.jsx
Labels: modify

#103 add, modify : 아이디, 비밀번호찾기 페이지 추가, 오타수정, 로그인성공시 바로 메인페이지로 이동(#99)
  src/api/membersApi.js
  src/pages/member/FindInfoPage.jsx
  src/pages/member/LoginPage.jsx
  src/util/jwtUtil.js
Labels: add, modify

#107 modify : 예매 페이지 리팩토링(#106)
  src/api/reservationApi.js
  src/components/layouts/MemberHeader.jsx
  src/components/reservation/CoupleModal.jsx
  src/components/reservation/ReservationResult.jsx
  src/components/reservation/SeatCount.jsx
  src/components/reservation/SeatTable.jsx
  src/components/reservation/TimeTableItem.jsx
  src/pages/mypage/MyCancelPage.jsx
  src/pages/mypage/MyReservationPage.jsx
  src/pages/mypage/MyReviewPage.jsx
  src/pages/reservation/ReservationSeatPage.jsx
  src/util/jwtUtil.js
Labels: modify

#110 add, modify : 아이디찾기, 비밀번호 재설정 기능추가
  src/api/membersApi.js
  src/pages/member/FindInfoPage.jsx
  src/pages/member/LoginPage.jsx
Labels: add, modify

#113 add : 예매관리 수정 및 추가 기능 구현
  src/pages/support/AdminMemberList.jsx
  src/pages/support/AdminReservationPage.jsx
Labels: add

#116 modify : movie, qna API수정
  src/api/movieApi.js
  src/api/qnaApi.js
  src/pages/admin/movie/AdminMovieRegisterPage.jsx
Labels: modify

#118 modify: 관람평 list 출력 완료(#12)
  src/pages/movie/MovieDetailPage.jsx
Labels: modify

#119 modify: 등록일 삭제(#12)
  src/pages/movie/MovieDetailPage.jsx
Labels: modify

#120 modify: 관리자adminReservation 수정, 메인페이지 인기순,최신순 정렬 수정, 테스트끝난 consol제거, …
  src/api/noticeApi.js
  src/api/reservationApi.js
  src/pages/MainPage.jsx
  src/pages/support/AdminReservationPage.jsx
  src/pages/support/NoticeListPage.jsx
Labels: modify

#123 feat : 관람평 영화티켓 인증 기능 추가(#122)
  src/components/mypage/MyReviewWrite.jsx
  src/components/python/ImageDetect.jsx
  src/pages/reservation/ReservationSuccessPage.jsx
Labels: feat

#126 modify: 영화 페이징네이션으로 수정(#12)
  src/api/movieApi.js
  src/pages/movie/MovieListPage.jsx
Labels: modify

#127 modify : 체크박스 미클릭시 회원가입이 되던 현상 수정
  src/pages/member/JoinPage.jsx
  src/pages/member/LoginPage.jsx
Labels: modify

#129 modify: 인기순 영화명 중복 제거 (#50)
  src/components/common/Search.jsx
  src/pages/MainPage.jsx
  src/pages/support/NoticeListPage.jsx
Labels: modify

#131 modify: 최신순 영화 목록의 정렬을 개봉일 순 및 중복영화 제거 수정(#50)
  src/pages/MainPage.jsx
Labels: modify

#133 modify : 관리자 영화 등록,수정 , 사용자 1:1문의 등록,수정 유효성 검사 추가
  src/pages/admin/movie/AdminMovieModifyPage.jsx
  src/pages/admin/movie/AdminMovieRegisterPage.jsx
  src/pages/support/QnaDetailPage.jsx
  src/pages/support/QnaRegisterPage.jsx
Labels: modify
